services:
  - type: web
    name: convertidor-mp3-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://convertidormp3.netlify.app
